postgresql:
  image: postgres:9.4
  ports:
    - 15432:5432
  volumes:
    - ~/develop/workspace/springboot-vue-boilerplate/postgres/data:/var/lib/postgresql/data
redis:
  image: redis
  ports:
    - 6379:6379
