spring:
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
#    datasource:
#        url: jdbc:postgresql://localhost:5432/<DB>
#        username: postgres
#        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
    session:
        store-type: redis
    redis:
        host: localhost
        port: 6379